global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'buginator-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    basic_auth:
      username: 'actuator'
      password: 'actuator'
    static_configs:
      - targets: ['buginator-auth:8080', 'buginator-gateway:8100']