buginator:
  actuator:
    credentials:
      username: actuator
      password: actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,caches,metrics,env,prometheus
  endpoint:
    health:
      show-details: always
server:
  port: 8100
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - OPTIONS
              - POST
              - PUT
              - PATCH
              - DELETE
              - HEAD
              - TRACE
            allowedHeaders: "*"
      routes:
        - id: oauth
          uri: http://localhost:8080
          predicates:
            - Path=/oauth/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: auth
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}